# Generated by Django 5.0.7 on 2024-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='service_images')),
                ('description', models.TextField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
