# Generated by Django 5.0.7 on 2024-07-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='about',
        ),
        migrations.RemoveField(
            model_name='service',
            name='header',
        ),
    ]
