# Generated by Django 5.0.7 on 2024-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_project_github_alter_project_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
